### ISSUE TITLE
webview debugging not working

### ISSUE THREAD

**Issue by danielegobbetti** [nailyk-fr/jenkins_scripts#5] opened 2018-02-23 07:59 UTC
Apologies if this issue is misplaced.

Using the ROM on my Z3C yields to the webview not being debuggable from the PC (using chrome://inspect). I detailed the issue here: http://jira.omnirom.org/browse/OMNI-1428

I am not using any Gapps, just the plain ROM. Can you please check if the problem is caused by something in the build scripts? I tried resetting the system settings, enabling and disabling the embedded chromium, but could not make it work.

Thanks a lot for your work!

**Comment by nailyk-fr** [comment] 2018-02-23 08:49
Problem is I have no idea what you are talking about ;)

What is your problem with the build script ? 
What version are you bulding?

**Comment by danielegobbetti** [comment] 2018-02-23 09:06
I am building omnirom 8.1 for my Z3C. I've long built sony AOSP and know a bit my way around it (I contributed a [patch](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch) for getting microG unified NLP work on android N. **I am not bragging**, I just want you to know that I kind-of know what I am talking about. :-)

If you take a look a the JIRA issue where I described the problem (issue that was just closed by you :-P )
, the steps to reproduce my problems are listed, but I will repeat them here:
- attach a Z3C running your omnirom 8.1 build to PC, connect adb
- open chrome/chromium on PC and go to ``chrome://inspect``
- you will get a list of applications that are using an integrated webview (examples: k9-mail, my own gadgetbridge, ...)
- if you follow the link you will get a 404 not found error, expected result is to see the webview as it is running on the device

This is caused by the Logcat output:
```
E chromium: [ERROR:devtools_http_handler.cc(249)] Cannot start http server for devtools. Stop devtools
```

As it might be that **I** caused the issue in my own build, but I am not messing with anything webview-related, I kindly ask if you could follow the steps I outlined above (should take no more than two minutes) to see if you can reproduce. If not I will re-check my whole setup again, if yes we can perhaps find the causes together.

> What is your problem with the build script ?

Possibly none, I opened a JIRA issue for my problem but it was being ignored and I wanted to bring it to your attention.

**Comment by nailyk-fr** [comment] 2018-02-23 09:29
> issue that was just closed by you :-P

Sorry! Jira is a proprietary crap, so totally not user friendly. Just reopened it. 

Ok thanks for explanation. Sadly I do not use chrome/chromium. 
Anyway this should not be device related. 
You could try to join freenode#omni to talk about your issue. 
Also, are you sure your setup is working fine on your computer (does this process works with another device ? )
Are you sure it do not require gapps (seems to be google specific)

**Comment by danielegobbetti** [comment] 2018-02-23 09:37
> Sorry! Jira is a proprietary crap, so totally not user friendly. Just reopened it.

No problem :)

> Also, are you sure your setup is working fine on your computer (does this process works with another device ? )
> Are you sure it do not require gapps (seems to be google specific)

Yes, for debugging gadgetbridge I use a spare galaxy nexus (nougat, pure AOSP) and a very old S4 mini (running ~~stock samsung cr_p~~ API 19), and both work wonders with my debian chromium web browser.

Further, I am fairly sure your build of OREO 8.0 of the beginning of the year still worked fine.

**Comment by nailyk-fr** [comment] 2018-02-23 10:08
(You can also build omni for maguro, check the 7.1 branch :p)
Closing here as it is definitively not a device issue.

**Comment by nailyk-fr** [comment] 2018-02-23 10:08
Migrated to http://jira.omnirom.org/browse/OMNI-1428

**Closed as completed by nailyk-fr** 2018-02-23 10:08 UTC

**Comment by danielegobbetti** [comment] 2018-02-23 10:27
Ok I posted my "steps to reproduce" comment there as well. Thanks for looking into it.
Please let me know if you can test with chromium. I will run the ZIP you distribute for Z3C "Verbatim" over the weekend to check if the problem is there.

**Comment by nailyk-fr** [comment] 2018-02-23 11:42
As you are using the build script you will produce the exact same ROM. 
I do not use/wont use chromium. 

Your other devices seems to be on stock ROM, so with gapps. 
Please test with gapps, then report into jira. 

Le 23 février 2018 11:27:42 GMT+01:00, Daniele Gobbetti <notifications@github.com> a écrit :
>Ok I posted my "steps to reproduce" comment there as well. Thanks for
>looking into it.
>Please let me know if you can test with chromium. I will run the ZIP
>you distribute for Z3C "Verbatim" over the weekend to check if the
>problem is there.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/nailyk-fr/jenkins_scripts/issues/5#issuecomment-367970949

-- 
Envoyé de mon appareil LineageOS avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by danielegobbetti** [comment] 2018-02-23 13:09
> Your other devices seems to be on stock ROM, so with gapps.

that's inaccurate. My galaxy nexus is not. I can try omnirom on it istead of AOSP, though.

> I do not use/wont use chromium.

Fair enough.

> Please test with gapps, then report into jira.

I do not use/wont use gapps.

**Comment by nailyk-fr** [comment] 2018-02-23 13:36
> that's inaccurate. My galaxy nexus is not. I can try omnirom on it istead of AOSP, though.
> I do not use/wont use gapps.

Ok so the lack of gapps is not the cause. Fine enough for me ;)
